# html lang
language: ja

# main menu navigation
menu:
  Home: /
  "プロフィール": /profile
  "記事一覧": /archives
  "このページについて": /about
rss: /atom.xml

# stylesheets loaded in the <head>
stylesheets:
- /css/shoyanblog.css

# scripts loaded in the end of the body
scripts:
- /js/shoyanblog.js
